# General
seed: 1234
cuda: False

# Training
epoch: 2

# DataLoader
batch_size: 32
shuffle: True

# Dataset
#dataset:
#  train:
#    MNIST:
#      root: './data'
#      train: True
#      download: True
#  valid:
#    MNIST:
#      root: './data'
#      train: False
#      download: True
dataset:
  train:
    L1000_basic:
      root: './data'
      train: True
      download: True
  valid:
    L1000_basic:
      root: './data'
      train: False
      download: True
  test:
    root: './data'
    train: False
    download: True

# Model
model:
  basic_AE:
    layers: [10, 10, 10]

# Optimizer
optimizer:
  Adam:
    lr: 0.001

# pytorch transform
transform:
  train:
    - ToTensor: {}
    - Normalize:
        mean: [0.1307]
        std: [0.3081]
  valid:
    - ToTensor: {}
    - Normalize:
        mean: [0.1307]
        std: [0.3081]
