# General
generic:
  exp_id: [1, 2, 3]
  seed: [1, 2, 3]
exp_id: 1
seed: 1
cuda: True

# Training
n_epochs: 200

# Early stopping
early_stopping: True
patience_max: 5

dataset:
  train:
    L1000_iid_env_split:
      phase: "both"
      batch_size: 32
      radius: 4
      nBits: 1024
#      restrict_to_envs_longer_than: 10
      train_val_test_prop: !!python/tuple [0.7,0.2,0.1]
  valid:
    L1000_iid_env_split:
      phase: "both"
      batch_size: 32
      radius: 4
      nBits: 1024
#      restrict_to_envs_longer_than: 10
      train_val_test_prop: !!python/tuple [0.7,0.2,0.1]

# Model
model:
  basic_VAE:
    enc_layers: [978, 500, 300]
    dec_layers: [300, 500, 978]
    beta: 1

# Optimizer
optimizer:
  Adam:
    lr: 0.0001