# Test all models in a simple setting
# General
generic:
#  exp_id: [4, 5, 6]
#  seed: [1, 2, 3]
exp_id: 3
seed: 5
cuda: False

# Training
n_epochs: 100

# Early stopping
early_stopping: True
patience_max: 4

dataset:
  train:
    L1000_iid_env_split:
      phase: "phase2"
      batch_size: 16
      restrict_to_envs_longer_than: 10
      train_val_test_prop: !!python/tuple [0.5,0.25,0.25]
  valid:
    L1000_iid_env_split:
      phase: "phase2"
      batch_size: 16
      restrict_to_envs_longer_than: 10
      train_val_test_prop: !!python/tuple [0.5,0.25,0.25]

# Model
model:
  conditional_VAE:
    enc_layers: [978, 500, 200]
    dec_layers: [200, 500, 978]
    condition_dim: 1024
#    aux_layers: [1024, 200]
    beta: 1

# Optimizer
optimizer:
  Adam:
    lr: 0.0003