# General
seed: 17
cuda: False

# Training
n_epochs: 100

dataset:
  train:
    L1000_n_env_per_batch:
      phase: "phase2"
      batch_size: 16
      restrict_to_envs_longer_than: 600
  valid:
    L1000_n_env_per_batch:
      phase: "phase2"
      batch_size: 16
      restrict_to_envs_longer_than: 600

# Model
model:
  basic_AE:
    layers: [978, 978]
#    beta: 0.001

# Optimizer
optimizer:
  Adam:
    lr: 0.0001
