# General
seed: 2
cuda: False

# Training
n_epochs: 100

dataset:
  train:
    synthetic_iid:
      n_hidden: 3
      n_observations: 10
      n_examples_per_env: 100
      n_envs: 10
      attach_proba: 0.2
      batch_size: 20
      train_val_test_prop: !!python/tuple [0.7,0.2,0.1]
  valid:
    synthetic_iid:
      n_hidden: 3
      n_observations: 10
      n_examples_per_env: 100
      n_envs: 10
      attach_proba: 0.2
      batch_size: 20
      train_val_test_prop: !!python/tuple [0.7,0.2,0.1]

# Model
model:
  env_VAE:
    layers: [10, 3]
    aux_layers: [3, 3]
    beta: 1

# Optimizer
optimizer:
  Adam:
    lr: 0.0001